### ISSUE TITLE
Can't detect mali version 401

### ISSUE THREAD

**Issue by white-gecko** [linux-sunxi/sunxi-mali#11]
Running `make config` it can't detect the version properly and outputs `UNKNOWN`, even though the `mali` module is loaded:

```
sunxi-mali$ sudo make config 
rm -f config.mk
make config.mk
make[1]: Entering directory '/home/me/sunxi-mali'
make -f Makefile.config
make[2]: Entering directory '/home/me/sunxi-mali'
ABI="armhf" (Detected)
VERSION="UNKNOWN" (Detected)
Makefile.config:57: Unknown/unhandled Mali Version "UNKNOWN"
Makefile.config:58: Use VERSION=(r2p4,r3p0,r3p1,r3p2-01rel1) instead
Makefile.config:59: *** Unknown/unhandled Mali Version "UNKNOWN".  Stop.
make[2]: Leaving directory '/home/me/sunxi-mali'
Makefile:12: recipe for target 'config.mk' failed
make[1]: *** [config.mk] Error 2
make[1]: Leaving directory '/home/me/sunxi-mali'
Makefile:8: recipe for target 'config' failed
make: *** [config] Error 2

$ lsmod 
Module                  Size  Used by
cpufreq_userspace       3548  0 
spidev                  6398  0 
sunxi_ss               17659  0 
hidp                   17562  0 
rfcomm                 58698  0 
hci_uart               25018  0 
bluetooth             265706  5 hidp,hci_uart,rfcomm
mali                  342892  0 
```

**Comment by white-gecko** [comment]
I've also made sure `/dev/mali` exists:

```
$ ls -l /dev/mali
crw-rw---- 1 root video 10, 50 Jan  1  2010 /dev/mali
```

**Comment by white-gecko** [comment]
Adding a new print statement to `version.c` gives me `Version is: 401`:

```
…
version = api_version.version & 0xFFFF;
fprintf(stderr, "Version is: %u\n", version);
for (i = 0; version_compat[i].compat; i++)
…
```

**Comment by white-gecko** [comment]
The above output is on an Alwinner A20 runnding this image: http://www.igorpecovnik.com/2014/11/18/olimex-lime-debian-sd-image/ while on the same board running the image provided by olimex: https://www.olimex.com/wiki/images/f/f3/A20_Lime_debian_3.4.90_release_2.torrent `version` returns `14` resp. `r3p0`, what does the version depend on? First I thought it is the hardware version, but now it looks as if it is some version of the kernel module?

**Comment by Achder** [comment]
I'm experiencing the exact same problem. Are there any updates on this issue? I tried the same modification of the version.c and also get a 401.

**Comment by ssvb** [comment]
For the igorpecovnik's kernels, this support request needs to be redirected to @dan-and
They are using mali kernel module version r4p0 for some reason: https://github.com/dan-and/linux-sunxi/commit/3740fc03da6d5722f64ccaf61783f0f8b712e79a

And because the mali kernel module and the mali userland blob must have exactly the same version, the r4p0 kernel module can't work with the userland blobs provided by CubieTech for the Allwinner hardware. You need to find the compatible userland blobs somewhere else.

**Comment by ssvb** [comment]
Closing, because we can't really do anything meaningful to resolve this problem. The VERSION="UNKNOWN" failure describes the situation correctly and is expected to happen.

Basically, everything would have been much better if ARM could provide up to date redistributable userland mali blobs: http://lists.linaro.org/pipermail/linaro-dev/2014-July/017352.html
ARM is providing blobs for Mali T series nowadays (with some strange license), but AFAIK nothing for Mali 400 is available directly from ARM yet.
